"""launches, raw_content, fetch_log

Revision ID: e2a4ce81c85e
Revises: 
Create Date: 2026-07-22 15:53:04.474657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2a4ce81c85e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_content',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('first_stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('fetch_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_hash'], ['raw_content.content_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fetch_log_url_fetched_at', 'fetch_log', ['url', 'fetched_at'], unique=False)
    op.create_table('launches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('launch_type', sa.String(length=32), nullable=False),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('property_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('unit_sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_from', sa.Float(), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('payment_plan', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.String(length=64), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['raw_content_hash'], ['raw_content.content_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_launches_project_developer', 'launches', ['project_name', 'developer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_launches_project_developer', table_name='launches')
    op.drop_table('launches')
    op.drop_index('ix_fetch_log_url_fetched_at', table_name='fetch_log')
    op.drop_table('fetch_log')
    op.drop_table('raw_content')
    # ### end Alembic commands ###
